require('lsp')
require('plugins.tagtree')
require('plugins.treesitter')
require('plugins.telescope')
-- require('plugins.cmp')
-- require('plugins.dap')
require('plugins.autopairs')
require('plugins.lualine')
require('plugins.barbar')
-- require('plugins.aerial-tags')
require('plugins.trouble')
require('plugins.todo')
